all:
  sf_media_browser:
    root_dir:           /uploads
    thumbnails_enabled:     false          # Enable thumbnail creation on upload (requires sfThumnailPlugin)
    thumbnails_dir:         .thumbnails    # Directory name for storing thumbnails
    thumbnails_max_width:   64
    thumbnails_max_height:  64


    file_types:                           # define file_types is usefull for displaying icons in browser
      document:                           # type of file (also used as default icon name)
        extensions: [doc, xls, xcf, ai]   # extensions associated to this type
        icon:       doc                   # optional icon file name, without extension
      image:                              
        extensions: [png, jpg, jpeg, gif] 
      pdf:
        extensions: [pdf]
      bin:
        extensions: [bin, exe, sh, bat, deb, yum]
      video:
        extensions: [wmv, avi, mpg, mpeg, flv, mp4]
      audio:
        extensions: [ogg, mp3, flac, wma, cda]
      text:
        extensions: [txt]
      tarball:
        extensions: [tar, gz, zip, bzip, gzip, rar, 7z]
  sfImageTransformPlugin:
    mime_type:
      auto_detect: true
        
