sf_media_browser:
  url:    sf_media_browser
  params: { module: sfMediaBrowser, action: index }

sf_media_browser_dir_create:
  url:    sf_media_browser_dir_create
  class:  sfRequestRoute
  params: { module: sfMediaBrowser, action: createDirectory }
  requirements: { sf_method: post }

sf_media_browser_dir_delete:
  url:    sf_media_browser_dir_delete
  class:  sfRequestRoute
  params: { module: sfMediaBrowser, action: deleteDirectory }
  requirements: { sf_method: get }

sf_media_browser_file_create:
  url:    sf_media_browser_file_create
  class:  sfRequestRoute
  params: { module: sfMediaBrowser, action: createFile }
  requirements: { sf_method: post }

sf_media_browser_file_delete:
  url:    sf_media_browser_file_delete
  class:  sfRequestRoute
  params: { module: sfMediaBrowser, action: deleteFile }
  requirements: { sf_method: get }

sf_media_browser_select:
  url:    sf_media_browser_select
  params: { module: sfMediaBrowser, action: select }